### ISSUE TITLE
undocumented zootool.com/api?

### ISSUE THREAD

**Issue by glaszig** [nicolascormier/ZTProxy#1]
would you mind sharing where you got the info about [all those undocumented](https://github.com/nicolascormier/ZTProxy/blob/master/ZTProxy.m#L49) api's?

**Comment by nicolascormier** [comment]
I've been working with the zootool guys for a while http://zootool.com/about

If you have any question regarding the API please let us know :)

**Comment by glaszig** [comment]
i see.
so, there's undocumented api - is there an endpoint for managing packs?

**Comment by nicolascormier** [comment]
You mean for adding/editing and deleting packs?

**Comment by glaszig** [comment]
exactly. 
generally, everything there is to manage the entire zoo would be great to know... :)

**Comment by nicolascormier** [comment]
OK we'll try to update the API document asap :)

in the meanwhile here are the queries I used for pack management

static NSString\* ZT_addPackURL = @"http://"ZTProxyServerHost@"/api/packs/add/?apikey=%@&login=%@&name=%@&icon=%@"; // args[4] : apikey, login, name, iconID

static NSString\* ZT_editPackURL = @"http://"ZTProxyServerHost@"/api/packs/edit/?apikey=%@&login=%@&id=%@&name=%@&icon=%@"; // args[5] : apikey, login, packID, name, iconID

static NSString\* ZT_removePackURL = @"http://"ZTProxyServerHost@"/api/packs/delete/?apikey=%@&login=%@&id=%@"; // args[3] : apikey, login, packID
